### PR TITLE
Bump for Pocketmine 3.9.0

### PR DESCRIPTION
**Pull request by Mohagames205**
In the pocketmine 3.9.0 update entity was renamed to actor in the protocols. So I renamed all datapackets with entity to actor.

### CODE REVIEW

**Comment by SuperAdam47** [comment]
[Server thread/CRITICAL]: Error: "Call to undefined method xenialdan\apibossbar\DiverseBossBar::sendActorDataPacket()" (EXCEPTION) in "C:/Users/aronf/Desktop/gereksiz şeyler/yedeksetup/GrandTheftDogs Sunucusu - PMMP 20.02.2019/virions/apibossbar-master/src/xenialdan/apibossbar/DiverseBossBar" at line 91

**Comment by Mohagames205** [comment]
@SuperAdam47 I already see what's wrong. I'll fix it asap

**Comment by Mohagames205** [comment]
@SuperAdam47 I fixed it :)

**Comment by SuperAdam47** [comment]
not fixed, i fixed #6

**Pull request closed without merging**
